import type { UpgradeDefinition, UpgradeState } from './types'

export const UPGRADES: UpgradeDefinition[] = [
  {
    id: 'click_boost_1',
    name: 'Enhanced Extractors',
    description: 'Boost energy per click',
    type: 'click',
    baseCost: 10,
    costScaling: 1.15,
    baseEffect: 1,
    effectScaling: 0,
  },
  {
    id: 'generator_solar',
    name: 'Solar Arrays',
    description: 'Generate +0.2 energy/sec passively',
    type: 'passive',
    baseCost: 15,
    costScaling: 1.12,
    baseEffect: 0.2,
    effectScaling: 0.04,
  },
  {
    id: 'generator_fusion',
    name: 'Fusion Reactors',
    description: 'Generate +1.5 energy/sec passively',
    type: 'passive',
    baseCost: 100,
    costScaling: 1.14,
    baseEffect: 1.5,
    effectScaling: 0.06,
  },
  {
    id: 'multiplier_efficiency',
    name: 'Efficiency Protocols',
    description: '+10% global multiplier per level',
    type: 'multiplier',
    baseCost: 200,
    costScaling: 1.30,
    baseEffect: 0.1,
    effectScaling: 0,
  },
  {
    id: 'generator_quantum',
    name: 'Quantum Harvesters',
    description: 'Generate +12 energy/sec passively',
    type: 'passive',
    baseCost: 1000,
    costScaling: 1.16,
    baseEffect: 12,
    effectScaling: 0.08,
  },
  {
    id: 'click_boost_2',
    name: 'Gravity Lenses',
    description: 'Mid-game click power boost',
    type: 'click',
    baseCost: 5000,
    costScaling: 1.20,
    baseEffect: 10,
    effectScaling: 0,
  },
  {
    id: 'multiplier_synergy',
    name: 'Synergy Matrix',
    description: '+5% multiplicative bonus per level',
    type: 'multiplier',
    baseCost: 10000,
    costScaling: 1.35,
    baseEffect: 0.05,
    effectScaling: 0,
  },
  {
    id: 'generator_antimatter',
    name: 'Antimatter Converters',
    description: 'Generate +100 energy/sec passively',
    type: 'passive',
    baseCost: 25000,
    costScaling: 1.18,
    baseEffect: 100,
    effectScaling: 0.08,
    gatedByResearch: 'res_antimatter_unlock',
  },
]

export function createInitialUpgradeStates(): UpgradeState[] {
  return UPGRADES.map((u) => ({ id: u.id, level: 0 }))
}
